#!/usr/bin/env python3
"""
generate_patient_meshes.py
===========================
For each TotalSegmentator subject folder, generates:

  1. patient_skin.obj        — smoothed skin surface mesh (for PyBullet)
  2. registration_meta.json  — affine/inv_affine/spacing for slice extractor
  3. bone_label.nii.gz       — merged binary bone mask (for 2-channel U-Net)

Expected input folder layout (TotalSegmentator v2):
  totalseg_patients/
    s0001/
      ct.nii.gz
      segmentations/
        body.nii.gz
        vertebrae_L1.nii.gz
        rib_left_1.nii.gz
        ...

Usage:
  python generate_patient_meshes.py --input-dir totalseg_patients --smooth-iter 10
"""

import argparse
import json
import time
from pathlib import Path

import nibabel as nib
import numpy as np
from skimage.measure import marching_cubes

# ── Bone structure names to merge ─────────────────────────────────────────────
BONE_STRUCTURES = [
    # Vertebrae
    "vertebrae_L5", "vertebrae_L4", "vertebrae_L3", "vertebrae_L2", "vertebrae_L1",
    "vertebrae_T12", "vertebrae_T11", "vertebrae_T10", "vertebrae_T9", "vertebrae_T8",
    "vertebrae_T7", "vertebrae_T6", "vertebrae_T5", "vertebrae_T4", "vertebrae_T3",
    "vertebrae_T2", "vertebrae_T1",
    # Ribs
    "rib_left_1", "rib_left_2", "rib_left_3", "rib_left_4", "rib_left_5",
    "rib_left_6", "rib_left_7", "rib_left_8", "rib_left_9", "rib_left_10",
    "rib_left_11", "rib_left_12",
    "rib_right_1", "rib_right_2", "rib_right_3", "rib_right_4", "rib_right_5",
    "rib_right_6", "rib_right_7", "rib_right_8", "rib_right_9", "rib_right_10",
    "rib_right_11", "rib_right_12",
    # Pelvis
    "sacrum", "hip_left", "hip_right",
    # Sternum / shoulders
    "sternum", "clavicula_left", "clavicula_right",
    "scapula_left", "scapula_right",
]


# ── Laplacian smoothing ───────────────────────────────────────────────────────
def laplacian_smooth(verts: np.ndarray, faces: np.ndarray,
                     n_iter: int = 10, lam: float = 0.5) -> np.ndarray:
    """
    Simple Laplacian smoothing to remove voxel staircase artefacts.
    Each vertex moves lambda * (mean_neighbour - vertex) per iteration.
    """
    print(f"    Smoothing mesh ({n_iter} iterations) …", end="", flush=True)
    verts = verts.copy()
    # Build adjacency: for each vertex collect its neighbours from face list
    adj = [set() for _ in range(len(verts))]
    for f in faces:
        adj[f[0]].update([f[1], f[2]])
        adj[f[1]].update([f[0], f[2]])
        adj[f[2]].update([f[0], f[1]])

    for _ in range(n_iter):
        new_verts = verts.copy()
        for i, nb in enumerate(adj):
            if nb:
                mean_nb = verts[list(nb)].mean(axis=0)
                new_verts[i] = verts[i] + lam * (mean_nb - verts[i])
        verts = new_verts

    print(" done")
    return verts


# ── OBJ exporter ──────────────────────────────────────────────────────────────
def export_obj(path: Path, verts: np.ndarray, faces: np.ndarray) -> None:
    """Write a simple Wavefront OBJ file (no materials, no UVs)."""
    with open(path, "w") as f:
        f.write("# Patient skin mesh generated by generate_patient_meshes.py\n")
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for fc in faces:
            # OBJ face indices are 1-based
            f.write(f"f {fc[0]+1} {fc[1]+1} {fc[2]+1}\n")


# ── Per-subject processing ─────────────────────────────────────────────────────
def process_subject(subj_dir: Path, smooth_iter: int, decimate: bool) -> bool:
    subj_id = subj_dir.name
    print(f"\n{'='*60}")
    print(f"  Processing subject: {subj_id}")
    print(f"{'='*60}")

    ct_path   = subj_dir / "ct.nii.gz"
    seg_dir   = subj_dir / "segmentations"

    if not ct_path.exists():
        print(f"  [SKIP] No ct.nii.gz found in {subj_dir}")
        return False
    if not seg_dir.exists():
        print(f"  [SKIP] No segmentations/ folder found in {subj_dir}")
        return False

    # ── Step 1: Load CT + affine ──────────────────────────────────────────────
    print("  [1/3] Loading CT volume ...")
    ct_img   = nib.load(str(ct_path))
    ct_vol   = np.asarray(ct_img.get_fdata(dtype=np.float32))
    affine   = ct_img.affine.astype(np.float64)
    inv_aff  = np.linalg.inv(affine)
    spacing  = np.array(ct_img.header.get_zooms()[:3], dtype=np.float64)
    ct_shape = list(ct_img.shape[:3])

    # ── Step 2: Merge bone segmentation masks first (used for component filtering) ──
    print("  [2/3] Merging bone segmentation masks ...")
    bone_vol = np.zeros(ct_shape, dtype=np.uint8)
    found_bones = 0
    for bone_name in BONE_STRUCTURES:
        bone_path = seg_dir / f"{bone_name}.nii.gz"
        if bone_path.exists():
            bv = np.asarray(nib.load(str(bone_path)).get_fdata(), dtype=np.float32)
            bone_vol |= (bv > 0.5).astype(np.uint8)
            found_bones += 1
    print(f"    Merged {found_bones}/{len(BONE_STRUCTURES)} bone structures")

    # Save bone label volume
    bone_nii = nib.Nifti1Image(bone_vol, affine)
    bone_out = subj_dir / "bone_label.nii.gz"
    nib.save(bone_nii, str(bone_out))
    print(f"    Saved: {bone_out}")

    # ── Step 3: Generate skin mesh ────────────────────────────────────────────
    # Derive body mask: threshold air (everything > -500 HU is tissue/bone/fluid)
    # then fill holes slice-by-slice
    print("  [3/3] Deriving body mask and generating skin mesh ...")
    from scipy.ndimage import label, binary_fill_holes, binary_erosion
    body_bin = (ct_vol > -500).astype(np.uint8)

    # First, seal the boundary slices by filling holes on the outer 2D boundary planes.
    # This caps internal cavities (lungs, stomach, bowel) that are open to the scan boundaries,
    # preventing them from leaking to the outside during full 3D/2D hole filling.
    body_bin[:, :, 0] = binary_fill_holes(body_bin[:, :, 0]).astype(np.uint8)
    body_bin[:, :, -1] = binary_fill_holes(body_bin[:, :, -1]).astype(np.uint8)
    body_bin[:, 0, :] = binary_fill_holes(body_bin[:, 0, :]).astype(np.uint8)
    body_bin[:, -1, :] = binary_fill_holes(body_bin[:, -1, :]).astype(np.uint8)
    body_bin[0, :, :] = binary_fill_holes(body_bin[0, :, :]).astype(np.uint8)
    body_bin[-1, :, :] = binary_fill_holes(body_bin[-1, :, :]).astype(np.uint8)

    # Run hole filling along all three orthogonal directions to fill all internal cavities completely
    for z in range(body_bin.shape[2]):
        body_bin[:, :, z] = binary_fill_holes(body_bin[:, :, z]).astype(np.uint8)
    for y in range(body_bin.shape[1]):
        body_bin[:, y, :] = binary_fill_holes(body_bin[:, y, :]).astype(np.uint8)
    for x in range(body_bin.shape[0]):
        body_bin[x, :, :] = binary_fill_holes(body_bin[x, :, :]).astype(np.uint8)

    # Clean body mask: select only the component overlapping with the bone segmentation
    # to completely eliminate scanner bed/table structures
    labeled, num_features = label(body_bin)
    bone_labels = labeled[bone_vol > 0]
    non_zero_labels = bone_labels[bone_labels > 0]
    if len(non_zero_labels) > 0:
        patient_label = np.bincount(non_zero_labels).argmax()
        body_bin = (labeled == patient_label).astype(np.uint8)
    else:
        # Fallback to largest component
        sizes = np.bincount(labeled.ravel())
        if len(sizes) > 1:
            body_bin = (labeled == sizes[1:].argmax() + 1).astype(np.uint8)

    # Light erosion to remove thin noise speckles on the surface
    body_bin = binary_erosion(body_bin, iterations=1).astype(np.uint8)

    # Pad the binary volume with a 1-voxel border of 0s to guarantee a closed mesh
    body_bin_padded = np.pad(body_bin, 1, mode='constant', constant_values=0)

    # Marching cubes on the padded binary body mask (voxel space)
    t0 = time.time()
    verts_vox, faces, _, _ = marching_cubes(body_bin_padded, level=0.5, step_size=2)

    # Invert winding order of faces to flip normals outwards (skimage gradient points inwards)
    faces = faces[:, [0, 2, 1]]

    # Subtract the 1-voxel padding offset to restore original voxel coordinates
    verts_vox = verts_vox - 1.0

    # Convert voxel indices → world mm using the affine
    n = verts_vox.shape[0]
    hom = np.hstack([verts_vox, np.ones((n, 1))])   # (N, 4)
    verts_mm = (affine @ hom.T).T[:, :3]            # (N, 3) in mm (RAS)

    # Convert mm → metres for PyBullet
    verts_m = verts_mm / 1000.0

    # Laplacian smoothing to remove voxel staircase
    verts_m = laplacian_smooth(verts_m, faces, n_iter=smooth_iter)

    # Compute centroid offset (PyBullet needs mesh centred at origin)
    centroid = verts_m.mean(axis=0)
    verts_centred = verts_m - centroid

    skin_path = subj_dir / "patient_skin.obj"
    export_obj(skin_path, verts_centred, faces)
    print(f"    Saved: {skin_path}  ({len(verts_m):,} verts, {len(faces):,} faces, {time.time()-t0:.1f}s)")


    # ── Step 4: Save registration_meta.json ───────────────────────────────────
    meta = {
        "affine":                affine.tolist(),
        "inv_affine":            inv_aff.tolist(),
        "ct_shape":              ct_shape,
        "voxel_spacing":         spacing.tolist(),
        "mesh_centering_offset": centroid.tolist(),
        "mesh_threshold_hu":     "TotalSegmentator-body-mask",
        "mesh_vertex_count":     len(verts_m),
        "mesh_face_count":       len(faces),
    }
    meta_path = subj_dir / "registration_meta.json"
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"    Saved: {meta_path}")

    return True


# ── Main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate patient_skin.obj, bone_label.nii.gz, and "
                    "registration_meta.json for TotalSegmentator subjects."
    )
    parser.add_argument(
        "--input-dir", type=Path, default=Path("totalseg_patients"),
        help="Root directory containing extracted TotalSegmentator subjects."
    )
    parser.add_argument(
        "--smooth-iter", type=int, default=10,
        help="Laplacian smoothing iterations for skin mesh (default: 10)."
    )
    parser.add_argument(
        "--subject", type=str, default=None,
        help="Process only this subject ID (e.g. s0001). Default: all."
    )
    args = parser.parse_args()

    input_dir = args.input_dir
    if not input_dir.exists():
        print(f"[ERROR] Input directory not found: {input_dir}")
        return

    # Collect subject directories
    if args.subject:
        subj_dirs = [input_dir / args.subject]
    else:
        subj_dirs = sorted([
            d for d in input_dir.iterdir()
            if d.is_dir() and d.name.startswith("s") and d.name[1:].isdigit()
        ])

    if not subj_dirs:
        print(f"[ERROR] No subject folders found in {input_dir}")
        return

    print(f"[info] Found {len(subj_dirs)} subject(s) to process: {[d.name for d in subj_dirs]}")

    ok = 0
    for subj_dir in subj_dirs:
        try:
            if process_subject(subj_dir, args.smooth_iter, decimate=False):
                ok += 1
        except Exception as e:
            print(f"  [ERROR] {subj_dir.name}: {e}")
            import traceback; traceback.print_exc()

    print(f"\n[done] Successfully processed {ok}/{len(subj_dirs)} subjects.")


if __name__ == "__main__":
    main()
